### ISSUE TITLE
top level documentation issues

### ISSUE THREAD

**Issue by dietmarkuehl** [bemanproject/beman#15]
I realise it is early days for the project. However, I think it is worth pointing out immediate issues on the existing content:

- The [FAQ link](https://github.com/beman-project/beman/blob/main/docs/faq.md), linked from [Project Beman](https://github.com/beman-project/beman) doesn't point anywhere (404). The links probably intended to go to [this file](https://github.com/beman-project/beman/blob/main/docs/FAQ.md) in some form (i.e., "faq" -> "FAQ").
- The [mission statement](https://github.com/beman-project/beman/blob/main/docs/missionstatement.md) linked from [Project Beman](https://github.com/beman-project/beman) just repeats the words as the paragraph it links from: I'm not convinced that is useful.
- The [License](https://github.com/beman-project/beman?tab=License-1-ov-file) has a headline reading "The LLVM Project is under the Apache License v2.0 with LLVM Exceptions:". I think "The LLVM Project" should read "The Beman Project". The "LLVM Exceptions" is probably OK as it is a term defined later in the license. There are further LLVM Project references at the end for third party software which should probably refer to the Beman Project, too.
- The [Governance page](https://github.com/beman-project/beman/blob/main/docs/governance.md) currently repeats the names of the Beman Leads right after stating them. I _guess_ that repetition was intended to be some kind of annotation.
- Apparently, there Discourse channel set up: I didn't see either a link or a way to request getting added.

**Comment by neatudarius** [comment]
I think this was completed in attached PRs. Thanks all for contribution!
