### ISSUE TITLE
Check all repos: codeowners,  review rules, labels

### ISSUE THREAD

**Issue by neatudarius** [bemanproject/beman#67]
Check all repos / entire org

- [x] CODEOWNERS
- [x] Review rules
- [x] Labels
   - [x] Org labels:
       - [x] `Beman Leads` - https://discourse.bemanproject.org/t/github-beman-leads-label-is-up/282 
       - [x] Default git labels

**Comment by wusatosi** [comment]
What do you mean by **review rules** here?

**Comment by wusatosi** [comment]
Also, what is the established tradition for who to add to codeowner?

**Comment by neatudarius** [comment]
> Also, what is the established tradition for who to add to codeowner?

Basically we should do periodically updates and add people who made major contributions on each component. Today I just added some org admins in few repos (which may need to approve changes not actually related to code - eg confugs etc).

Would you like to append yourself into the exemplar CODEOWNERS files? I will approve that. I think you should be notified if changes are pushed for infrastructure bits there.

**Comment by wusatosi** [comment]
> > What do you mean by **review rules** here?
> 
> I found that some repos are not configured to require PR review.

Oh wow I didn't know that could be tuned off

**Comment by neatudarius** [comment]
> > > What do you mean by **review rules** here?
> > 
> > 
> > I found that some repos are not configured to require PR review.
> 
> Oh wow I didn't know that could be tuned off

It seems that when use exampler as a template projects, settings are not cloned. This is why I created this issue. I will check multiple things after Poland meeting.

**Comment by wusatosi** [comment]
> [repo rules not propagated when using exemplar as template ]

Yeah it really sucks there no programtic way to configure GitHub repo. 

We do need a standard for generic GitHub repo settings. 

> [Adding myself to codeowner]

Yeah definitely. I would love to. 
I am steering myself to work more on the cpp library side, so it would definitely be nice to have me pinned on infrastructure based edits.

**Comment by neatudarius** [comment]
> > > What do you mean by **review rules** here?
> > 
> > 
> > I found that some repos are not configured to require PR review.
> 
> I don't think you need to enable this?? https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners

Yes. Enforce people not be able to merge a PR without codeowners approval must be configured.

**Comment by wusatosi** [comment]
> Enforce people not be able to merge a PR without codeowners approval must be configured.

Do you want me to leave a comment in CODEOWNERS file?

**Comment by neatudarius** [comment]
> > Enforce people not be able to merge a PR without codeowners approval must be configured.
> 
> Do you want me to leave a comment in CODEOWNERS file?

No. As an admin I must configure each repo (or find a way to enforce in org) that git actually reads thats file.

If the file is present but the repo settings for "require review from codeowners before approval " is disabled, it's like anybody can merge a PR!

**Comment by wusatosi** [comment]
> > > Enforce people not be able to merge a PR without codeowners approval must be configured.
> > 
> > 
> > Do you want me to leave a comment in CODEOWNERS file?
> 
> No. As an admin I must configure each repo (or find a way to enforce in org) that git actually reads thats file.
> 
> If the file is present but the repo settings for "require review from codeowners before approval " is disabled, it's like anybody can merge a PR!

Yeah I mean leave a note in CODEOWNERS, basically saying: `when you first use this template, please don't forget to turn on this repo setting`.

Ah...

We need a "after creating a repo checklist".

**Comment by wusatosi** [comment]
> Would you like to append yourself into the exemplar CODEOWNERS files? I will approve that. I think you should be notified if changes are pushed for infrastructure bits there.

btw: https://github.com/bemanproject/exemplar/pull/83

**Comment by neatudarius** [comment]
Current states is good enough. Future updates will made with https://github.com/bemanproject/infra/issues/1
